# Generated by Django 4.2.26 on 2025-11-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShotAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="uploads/")),
                (
                    "processed_video",
                    models.FileField(blank=True, null=True, upload_to="processed/"),
                ),
                ("club", models.CharField(blank=True, max_length=64)),
                (
                    "distance",
                    models.FloatField(
                        blank=True, help_text="Distance in yards", null=True
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(
                        blank=True, help_text="Accuracy score (0-100)", null=True
                    ),
                ),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("result_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="shot",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
