# Generated by Django 4.2.26 on 2025-11-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shots", "0002_shotanalysis_alter_shot_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shot",
            name="club",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="shotanalysis",
            name="club",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
