# Generated by Django 4.2.26 on 2025-11-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shots", "0003_alter_shot_club_alter_shotanalysis_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shot",
            name="club",
            field=models.CharField(blank=True, default="", max_length=64, null=True),
        ),
    ]
