# Generated by Django 4.2.26 on 2025-11-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shots", "0004_alter_shot_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shot",
            name="club",
            field=models.CharField(blank=True, default="Unknown", max_length=64),
        ),
    ]
