# Generated by Django 4.2.26 on 2025-11-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shots", "0005_alter_shot_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shotanalysis",
            name="club",
            field=models.CharField(blank=True, default="Unknown", max_length=100),
        ),
    ]
