# Generated by Django 4.2.26 on 2025-12-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shots", "0005_shotanalysis_selected_tee_shotanalysis_used_tee"),
    ]

    operations = [
        migrations.AddField(
            model_name="shotanalysis",
            name="hole_par",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
