# Generated by Django 4.2.26 on 2025-12-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shots", "0006_shotanalysis_hole_par"),
    ]

    operations = [
        migrations.AddField(
            model_name="shotanalysis",
            name="thumbnail",
            field=models.FileField(blank=True, null=True, upload_to="thumbnails/"),
        ),
    ]
