# Generated by Django 4.2.26 on 2025-11-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shots", "0006_alter_shotanalysis_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shotanalysis",
            name="distance",
            field=models.CharField(
                blank=True, help_text="Distance (text)", max_length=50, null=True
            ),
        ),
    ]
