# Generated by Django 4.2.25 on 2025-11-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shots", "0008_update_shotanalysis_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="shotanalysis",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="First frame thumbnail",
                null=True,
                upload_to="thumbnails/",
            ),
        ),
        migrations.AlterField(
            model_name="shotanalysis",
            name="input_video",
            field=models.FileField(upload_to="input/"),
        ),
    ]
