# Generated by Django 4.2.26 on 2025-12-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shots", "0013_shotanalysis_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shotanalysis",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
