# Generated by Django 4.2.26 on 2025-12-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shots", "0016_coursemetadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="shotanalysis",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
    ]
