# Generated by Django 4.2.25 on 2025-12-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shots", "0017_shotanalysis_is_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="shotanalysis",
            name="probe_creation_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
