# Generated by Django 4.2.25 on 2025-12-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shots", "0018_shotanalysis_probe_creation_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="shotanalysis",
            name="client_added_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
