# Generated by Django 4.2.25 on 2025-12-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shots", "0021_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="tee_names_json",
            field=models.TextField(
                blank=True, help_text="JSON list of tee names from API", null=True
            ),
        ),
    ]
