# Generated by Django 4.2.26 on 2026-01-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shots", "0023_shotanalysis_overlay_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="shotanalysis",
            name="include_course_text",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shotanalysis",
            name="include_map",
            field=models.BooleanField(default=False),
        ),
    ]
