# Generated by Django 4.2.25 on 2026-01-26 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shots", "0026_holepin"),
        ("shots", "0027_alter_holepin_id_alter_holepin_user_and_more"),
    ]

    operations = []
