# Generated by Django 4.2.25 on 2026-01-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shots", "0028_merge_20260126_2317"),
    ]

    operations = [
        migrations.AddField(
            model_name="shotround",
            name="selected_tee",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
